### ISSUE TITLE
Why this project is abandoned (at least looks like it)?

### ISSUE THREAD

**Issue by sergey-lapin** [ForbesLindesay/flow-babel-types#2]
This seems to me as totally reasonable idea to be babel-typed typed (sorry for repetition hah). I just wonder whether you don't have time on this project, or you disappointed in idea itself for some reason?  @ForbesLindesay

**Comment by sergey-lapin** [comment]
I did not found any typings expect yours out there, flow-typed does not have babel-typed neither, maybe I am blind.

**Comment by ForbesLindesay** [comment]
This project is essentially "finished". The new `@babel/types` exports flow types of its own, making this library obsolete. anyway.
